# Simple deployment used to deploy and manage the app in nigelpoulton/getting-started-k8s:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-deploy
  labels:
    app: express-api
spec:
  replicas: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: express-api-pod
        image: anilshirole/gsd:espressapi2024
        imagePullPolicy: Always
        ports:
        - containerPort: 3001