apiVersion: v1
kind: Service
metadata:
  name: express-api-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3001
    nodePort: 31112
    protocol: TCP
  selector:
    app: express-api
    